#!/usr/bin/env perl

# Author: @nullriver
# Purpose: Compiles a Cydia repository

use Digest::MD5;
 
sub md5sum {   
    my $file = shift;
    my $digest = "";
    eval {
        open(FILE, $file) or die "Can't find file $file\n";
        my $ctx = Digest::MD5->new;
        $ctx->addfile(*FILE);
        $digest = $ctx->hexdigest;
        close(FILE);
    };
    if ($@) {
        print $@;
        return ""; 
    }  
    return $digest;
}

# build packages into deb/ 
system("chmod 0755 uncompiled-packages/ -R");

my $directory = 'uncompiled-packages/';
opendir (DIR, $directory) or die $!;
while (my $file = readdir(DIR)) {
	system("dpkg -b uncompiled-packages/".$file." deb/".$file.".deb");
}
closedir(DIR);

# scan the packages and write output to file Packages 
system("dpkg-scanpackages deb / > Packages");

# bzip2 it to a new file 
system("bzip2 -fks Packages");

# scan again because we zipped the original file  
system("dpkg-scanpackages deb / > Packages");

# calculate the hashes and write to Release  
system("cp Release-Template Release");
open(RLS, ">>Release");

@files = ("Packages", "Packages.bz2");
my $output = "";

foreach (@files) {
 	my $fname = $_;
	my $md5 =  md5sum($fname);
	my $size = -s $fname;
	$output = $output.$md5." ".$size." ".$fname."\n";
};

print RLS $output;
close(RLS);

system("find . -name ‘*.DS_Store’ -type f -delete");

system("git add . && git commit -m 'Update repo - automated' && git push");

exit 0;